services:
  - type: web
    name: loan-approval-predictor
    runtime: python
    buildCommand: pip3 install -r requirements.txt && python3 -m src.model_training
    startCommand: python3 -m streamlit run streamlit_app.py --server.port $PORT --server.address 0.0.0.0 --server.headless true
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
